"use client";

import { Suspense, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useLocale, useTranslations } from "next-intl";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";

import { resetPassword } from "@/lib/auth-client";
import { mapAuthError } from "@/lib/map-auth-error";
import { checkPasswordRules, PASSWORD_MIN_LENGTH } from "@/lib/password-rules";
import { AuthShell } from "@/components/auth/auth-shell";
import { FormErrorBanner } from "@/components/auth/form-error-banner";
import { LogoSpinner } from "@/components/auth/logo-spinner";
import { PasswordRuleRow } from "@/components/auth/password-rule-row";
import { Button } from "@/components/ui/button";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { PasswordInput } from "@/components/ui/password-input";

const resetSchema = z.object({
  newPassword:     z.string().min(1),
  confirmPassword: z.string().min(1),
});
type ResetValues = z.infer<typeof resetSchema>;

/** Suspense: useSearchParams() reads `?token=` — see the same note on login/page.tsx. */
export default function ResetPasswordPage() {
  return (
    <Suspense fallback={null}>
      <ResetContent />
    </Suspense>
  );
}

function ResetContent() {
  const t = useTranslations("auth");
  const locale = useLocale();
  const router = useRouter();
  const searchParams = useSearchParams();
  // better-auth appends this itself to the `redirectTo` given to
  // requestPasswordReset (forgot/page.tsx) once the emailed link is
  // clicked — not generated by this app.
  const token = searchParams.get("token");

  const [serverError, setServerError] = useState<string | null>(null);
  const [done, setDone] = useState(false);

  const form = useForm<ResetValues>({
    resolver: zodResolver(resetSchema),
    defaultValues: { newPassword: "", confirmPassword: "" },
  });

  const newPassword = form.watch("newPassword");
  const passwordCheck = checkPasswordRules(newPassword);

  async function onSubmit(values: ResetValues) {
    setServerError(null);
    if (!passwordCheck.valid) {
      form.setError("newPassword", { message: t("errors.weakPassword") });
      return;
    }
    if (values.newPassword !== values.confirmPassword) {
      form.setError("confirmPassword", { message: t("errors.passwordMismatch") });
      return;
    }
    if (!token) return; // guarded by the early return below; unreachable in practice

    const { error } = await resetPassword({ newPassword: values.newPassword, token });
    if (error) {
      setServerError(mapAuthError(error, t));
      return;
    }
    setDone(true);
    setTimeout(() => router.push(`/${locale}/auth/login`), 2000);
  }

  if (!token) {
    return (
      <AuthShell locale={locale} hideTabs>
        <h2 className="auth-title" id="authTitle">{t("resetTitle")}</h2>
        <div className="grid gap-4">
          <FormErrorBanner message={t("resetInvalidToken")} />
          <Link href={`/${locale}/auth/forgot`} className="text-center text-sm text-muted-foreground underline underline-offset-4">
            {t("forgotTitle")}
          </Link>
        </div>
      </AuthShell>
    );
  }

  if (done) {
    return (
      <AuthShell locale={locale} hideTabs>
        <h2 className="auth-title" id="authTitle">{t("resetTitle")}</h2>
        <p className="text-sm text-success" role="status">
          {t("resetButton")} ✓
        </p>
      </AuthShell>
    );
  }

  return (
    <AuthShell locale={locale} hideTabs>
      <h2 className="auth-title" id="authTitle">{t("resetTitle")}</h2>
      <p className="auth-subtitle">{t("resetMessage")}</p>

      {serverError ? <FormErrorBanner message={serverError} className="mb-4" /> : null}
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="grid gap-4">
          <FormField
            control={form.control}
            name="newPassword"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t("newPassword")}</FormLabel>
                <FormControl>
                  <PasswordInput autoComplete="new-password" {...field} />
                </FormControl>
                <ul className="grid gap-1 text-xs">
                  <PasswordRuleRow
                    ok={newPassword.length >= PASSWORD_MIN_LENGTH}
                    label={t("passwordRules.minLength")}
                  />
                  <PasswordRuleRow ok={/[A-Z]/.test(newPassword)} label={t("passwordRules.uppercase")} />
                  <PasswordRuleRow ok={/[0-9]/.test(newPassword)} label={t("passwordRules.digit")} />
                </ul>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name="confirmPassword"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t("confirmPassword")}</FormLabel>
                <FormControl>
                  <PasswordInput autoComplete="new-password" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <Button
            type="submit"
            disabled={form.formState.isSubmitting}
            aria-busy={form.formState.isSubmitting}
            className="auth-submit-btn h-12 w-full rounded-xl text-[0.92rem]"
          >
            {form.formState.isSubmitting ? <LogoSpinner variant="signin" /> : t("resetButton")}
          </Button>
        </form>
      </Form>
    </AuthShell>
  );
}
